import { DiscordApi } from "./api.js";
import { permissionNames, permissionValue } from "./permissions.js";
function colorInt(value){if(value===undefined)return undefined;if(typeof value==="number")return value;return Number.parseInt(String(value).replace("#",""),16);}
export class DiscordService {
  constructor(){this.secrets=null;this.api=null;this.user=null;this.guild=null;}
  async connect(secrets){const api=new DiscordApi(secrets.discordBotToken);const [user,guild]=await Promise.all([api.get("/users/@me"),api.get(`/guilds/${secrets.guildId}?with_counts=true`)]);this.secrets=secrets;this.api=api;this.user=user;this.guild=guild;return{botName:user.username,serverName:guild.name};}
  disconnect(){this.secrets=this.api=this.user=this.guild=null;}
  connected(){return Boolean(this.api&&this.guild&&this.user)}
  require(){if(!this.api||!this.secrets||!this.guild||!this.user)throw new Error("Discord bot is not connected.");return{api:this.api,secrets:this.secrets,guild:this.guild,user:this.user};}
  async snapshot(){const{api,secrets,guild,user}=this.require();const[roles,channels,member]=await Promise.all([api.get(`/guilds/${secrets.guildId}/roles`),api.get(`/guilds/${secrets.guildId}/channels`),api.get(`/guilds/${secrets.guildId}/members/${user.id}`)]);const memberRoleIds=new Set(member.roles||[]);const botRoles=roles.filter(r=>memberRoleIds.has(r.id));const highest=botRoles.reduce((m,r)=>Math.max(m,r.position),0);let botPerm=0n;for(const r of roles)if(r.id===secrets.guildId||memberRoleIds.has(r.id))botPerm|=BigInt(r.permissions||0);return{guild:{id:guild.id,name:guild.name,memberCount:guild.approximate_member_count||0,ownerId:guild.owner_id},bot:{id:user.id,username:user.username,highestRolePosition:highest,permissions:permissionNames(botPerm)},roles:roles.map(r=>({id:r.id,name:r.name,position:r.position,permissions:permissionNames(r.permissions),managed:r.managed})).sort((a,b)=>b.position-a.position),channels:channels.map(c=>({id:c.id,name:c.name,type:typeName(c.type),parentId:c.parent_id||null,position:c.position||0,topic:c.topic||null,permissionOverwrites:(c.permission_overwrites||[]).map(o=>({id:o.id,type:o.type===0?"role":"member",allow:permissionNames(o.allow),deny:permissionNames(o.deny)}))})).sort((a,b)=>a.position-b.position)};}
  async raw(){const s=await this.snapshot();return s;}
  async resolveRole(name,id){const s=await this.snapshot();const role=id?s.roles.find(r=>r.id===id):name==="@everyone"?s.roles.find(r=>r.id===s.guild.id):s.roles.find(r=>r.name===name);if(!role)throw new Error(`Role not found: ${id||name}`);return role;}
  async resolveChannel(name,id,categoryName){const s=await this.snapshot();let pool=s.channels;if(categoryName){const cat=pool.find(c=>c.name===categoryName&&c.type==="category");pool=pool.filter(c=>c.parentId===cat?.id)}const channel=id?pool.find(c=>c.id===id):pool.find(c=>c.name===name);if(!channel)throw new Error(`Channel not found: ${id||name}`);return channel;}
  async overwrites(items=[]){const s=await this.snapshot();const out=[];for(const item of items){const role=item.roleName==="@everyone"?s.roles.find(r=>r.id===s.guild.id):s.roles.find(r=>r.name===item.roleName);if(!role)throw new Error(`Role not found for overwrite: ${item.roleName}`);out.push({id:role.id,type:0,allow:permissionValue(item.allow),deny:permissionValue(item.deny)});}return out;}
  async execute(a){const{api,secrets}=this.require();const s=await this.snapshot();const me=s.bot;
    switch(a.type){
      case"CREATE_ROLE":{if(!a.name)throw new Error("Role name required.");const existing=s.roles.find(r=>r.name===a.name);if(existing)return`Role already exists: ${a.name}`;const r=await api.post(`/guilds/${secrets.guildId}/roles`,{name:a.name,permissions:permissionValue(a.permissions),color:colorInt(a.color),hoist:a.hoist||false,mentionable:a.mentionable||false});return`Created role ${r.name}`;}
      case"UPDATE_ROLE":{const r=await this.resolveRole(a.name,a.targetId);if(r.position>=me.highestRolePosition)throw new Error("Bot cannot edit a role at or above its highest role.");const x=await api.patch(`/guilds/${secrets.guildId}/roles/${r.id}`,clean({name:a.newName,permissions:a.permissions?permissionValue(a.permissions):undefined,color:colorInt(a.color),hoist:a.hoist,mentionable:a.mentionable}));return`Updated role ${x.name}`;}
      case"DELETE_ROLE":{const r=await this.resolveRole(a.name,a.targetId);if(r.managed||r.id===s.guild.id)throw new Error("Managed or @everyone role cannot be deleted.");if(r.position>=me.highestRolePosition)throw new Error("Bot cannot delete this role due to hierarchy.");await api.delete(`/guilds/${secrets.guildId}/roles/${r.id}`);return`Deleted role ${r.name}`;}
      case"CREATE_CATEGORY":{if(!a.name)throw new Error("Category name required.");if(s.channels.some(c=>c.name===a.name&&c.type==="category"))return`Category already exists: ${a.name}`;const c=await api.post(`/guilds/${secrets.guildId}/channels`,{name:a.name,type:4,permission_overwrites:await this.overwrites(a.permissionOverwrites)});return`Created category ${c.name}`;}
      case"CREATE_TEXT_CHANNEL":case"CREATE_VOICE_CHANNEL":{if(!a.name)throw new Error("Channel name required.");const category=a.categoryName?s.channels.find(c=>c.name===a.categoryName&&c.type==="category"):null;if(a.categoryName&&!category)throw new Error(`Category not found: ${a.categoryName}`);if(s.channels.some(c=>c.name===a.name&&c.parentId===(category?.id||null)))return`Channel already exists: ${a.name}`;const c=await api.post(`/guilds/${secrets.guildId}/channels`,clean({name:a.name,type:a.type==="CREATE_TEXT_CHANNEL"?0:2,parent_id:category?.id,topic:a.type==="CREATE_TEXT_CHANNEL"?a.topic:undefined,permission_overwrites:await this.overwrites(a.permissionOverwrites)}));return`Created channel ${c.name}`;}
      case"UPDATE_CATEGORY":case"UPDATE_CHANNEL":{const c=await this.resolveChannel(a.name,a.targetId,a.categoryName);const x=await api.patch(`/channels/${c.id}`,clean({name:a.newName,topic:a.topic,position:a.position}));return`Updated channel ${x.name}`;}
      case"MOVE_CHANNEL":{const c=await this.resolveChannel(a.name,a.targetId);const cat=a.categoryName?s.channels.find(x=>x.name===a.categoryName&&x.type==="category"):null;if(a.categoryName&&!cat)throw new Error(`Category not found: ${a.categoryName}`);await api.patch(`/channels/${c.id}`,{parent_id:cat?.id||null});if(a.position!==undefined)await api.patch(`/guilds/${secrets.guildId}/channels`,[{id:c.id,position:a.position,parent_id:cat?.id||null}]);return`Moved channel ${c.name}`;}
      case"DELETE_CATEGORY":{const c=await this.resolveChannel(a.name,a.targetId);if(c.type!=="category")throw new Error("Target is not a category.");if(s.channels.some(x=>x.parentId===c.id))throw new Error("Category must be empty before deletion.");await api.delete(`/channels/${c.id}`);return`Deleted category ${c.name}`;}
      case"DELETE_CHANNEL":{const c=await this.resolveChannel(a.name,a.targetId,a.categoryName);await api.delete(`/channels/${c.id}`);return`Deleted channel ${c.name}`;}
      case"SET_CHANNEL_PERMISSIONS":{const c=await this.resolveChannel(a.name,a.targetId,a.categoryName);for(const o of a.permissionOverwrites||[]){const r=await this.resolveRole(o.roleName);await api.put(`/channels/${c.id}/permissions/${r.id}`,{type:0,allow:permissionValue(o.allow),deny:permissionValue(o.deny)});}return`Updated permissions for ${c.name}`;}
      case"SEND_MESSAGE":{const c=await this.resolveChannel(a.name,a.targetId,a.categoryName);const m=await api.post(`/channels/${c.id}/messages`,{content:a.content||""});return`Sent message ${m.id} in ${c.name}`;}
      case"EDIT_MESSAGE":{if(!a.messageId)throw new Error("messageId required.");const c=await this.resolveChannel(a.name,a.targetId,a.categoryName);const m=await api.get(`/channels/${c.id}/messages/${a.messageId}`);if(m.author.id!==s.bot.id)throw new Error("Bot can edit only its own messages.");await api.patch(`/channels/${c.id}/messages/${a.messageId}`,{content:a.content||""});return`Edited message ${a.messageId}`;}
      case"DELETE_MESSAGE":{if(!a.messageId)throw new Error("messageId required.");const c=await this.resolveChannel(a.name,a.targetId,a.categoryName);await api.delete(`/channels/${c.id}/messages/${a.messageId}`);return`Deleted message ${a.messageId}`;}
      case"ASSIGN_MEMBER_ROLE":case"REMOVE_MEMBER_ROLE":{if(!a.memberId||!a.roleName)throw new Error("memberId and roleName required.");const r=await this.resolveRole(a.roleName);if(r.position>=me.highestRolePosition)throw new Error("Bot cannot manage this role due to hierarchy.");const p=`/guilds/${secrets.guildId}/members/${a.memberId}/roles/${r.id}`;if(a.type==="ASSIGN_MEMBER_ROLE")await api.put(p);else await api.delete(p);return`${a.type==="ASSIGN_MEMBER_ROLE"?"Assigned":"Removed"} ${r.name}`;}
      default:throw new Error(`Unsupported action: ${a.type}`);
    }}
}
function clean(v){return Object.fromEntries(Object.entries(v).filter(([,x])=>x!==undefined));}
function typeName(t){return({0:"text",2:"voice",4:"category",5:"announcement",10:"announcement-thread",11:"public-thread",12:"private-thread",13:"stage",15:"forum",16:"media"})[t]||String(t)}
export const discord=new DiscordService();
export async function testDiscord(secrets){const temp=new DiscordService();const info=await temp.connect(secrets);const snap=await temp.snapshot();temp.disconnect();const permissions=permissionValue(["ViewChannel","SendMessages","ReadMessageHistory","ManageChannels","ManageRoles","ManageMessages","ManageGuild"]);return{...info,permissions:snap.bot.permissions,inviteUrl:`https://discord.com/oauth2/authorize?client_id=${encodeURIComponent(secrets.discordClientId)}&scope=bot&permissions=${permissions}`};}
